name: Release new version
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'
jobs:
  release:
    name: Publish artefacts
    runs-on: ubuntu-latest

    steps:
      - name: Extract version from tag name
        run: |
          VERSION=`echo ${GITHUB_REF##*/} | sed 's/^.//'`
          # make it available to all subsequent jobs
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          echo "Releasing version: ${VERSION}"

      - name: Checkout source
        uses: actions/checkout@v4
        # https://github.com/actions/checkout

      - name: Create release branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          RELEASE_BRANCH="release/${VERSION}"
          
          git switch -c ${RELEASE_BRANCH}
          
          # update version in build.gradle
          sed -i "s/^\s*version\s*=\s*'<unreleased>'/\tversion = '${VERSION}'/" build.gradle
          git add build.gradle
          
          git commit -m 'Release ${VERSION}'

          git push origin "${RELEASE_BRANCH}"

      - name: Create a GitHub Release
        uses: elgohr/Github-Release-Action@v5
        # https://github.com/elgohr/Github-Release-Action
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ env.VERSION }}
          tag: release-${{ env.VERSION }}

      - name: Setup Java environment
        uses: actions/setup-java@v4
        # https://github.com/actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and package distribution
        run: |
          ./gradlew --exclude-task test --no-daemon build

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build canary-server container image
        run: |
          podman build --tag ghcr.io/gkresic/canary-server:$VERSION canary-server/

      - name: Push canary-server container image to GitHub Container Registry
        run: |
          podman push ghcr.io/gkresic/canary-server:$VERSION
          # also tag and push as 'latest'
          podman tag ghcr.io/gkresic/canary-server:$VERSION ghcr.io/gkresic/canary-server:latest
          podman push ghcr.io/gkresic/canary-server:latest